### ISSUE TITLE
[Question] How do you know that by default all the keys are 0x00?

### ISSUE THREAD

**Issue by creeefs** [johnnyb/nfc-dna-kit#1]
👋 ,

This library looks awesome. I was going through [NTAG 424 DNA Data Sheet](https://www.nxp.com/docs/en/data-sheet/NT4H2421Gx.pdf), and I don't see any info on the default master and application keys. Was wondering how you knew it was set to `00`.

Thanks!

**Comment by johnnyb** [comment]
When I bought them I asked :)  I don't think it's part of the spec, and you can actually ask them to preload other keys onto them, but the default seems to be all 0s.

**Comment by creeefs** [comment]
Gotcha, thanks for the insight!
