### ISSUE TITLE
[Question] Are the session keys needed after authenticating via `authenticateEV2First`?

### ISSUE THREAD

**Issue by creeefs** [johnnyb/nfc-dna-kit#2]
👋  Hello,

From looking at the code for `authenticateEV2First`, it doesn't seem like you're extracting the session keys. Are the session keys not needed for future requests?

Thanks!
Chris

**Comment by johnnyb** [comment]
Sorry I missed this.  The session keys are indeed used - they are stored in the AESEncryptionMode class.  This is because the session keys are stored differently on AES and LRP.  AES has two session keys (and encryption key and a MAC key), while LRP has one key which is used for both.

**Comment by johnnyb** [comment]
Basically, when I implement the authenticateLRPFirst, it will instantiate a different class for the sessionEncryptionMode variable, which will be setup for LRP instead of AES.
